// Service pages. Each entry renders /services/<slug>/ and a card on /services/.

export const services = [
  {
    slug: 'accounting-bookkeeping',
    name: 'Accounting & Bookkeeping',
    icon: 'fas fa-book-open',
    summary: 'Accurate monthly books, management accounts and annual financial statements you can take to the bank.',
    lead: 'Accurate, up-to-date books and financial statements you can rely on: for ZIMRA, for your bank and investors, and for your own decisions.',
    intro: [
      'Good decisions start with good numbers. We keep your books current every month, reconcile every account and turn the figures into clear reports that show how your business is really doing.',
      'Whether you need a monthly bookkeeping routine, a set of annual financial statements for the bank, or help clearing years of backlog before an audit, our team handles it properly and on time.',
    ],
    included: [
      { icon: 'fas fa-receipt', title: 'Monthly bookkeeping', text: 'Sales, purchases, expenses and receipts captured and categorised every month, so your records are always current.' },
      { icon: 'fas fa-scale-balanced', title: 'Reconciliations', text: 'Bank, cash, supplier and customer accounts reconciled monthly, so errors and missing payments are caught early.' },
      { icon: 'fas fa-chart-pie', title: 'Management accounts', text: 'Monthly or quarterly profit and loss, balance sheet and cash-flow reports with plain-language commentary.' },
      { icon: 'fas fa-file-contract', title: 'Annual financial statements', text: 'Year-end financial statements prepared in line with International Financial Reporting Standards, ready for ZIMRA, banks and shareholders.' },
      { icon: 'fas fa-magnifying-glass-chart', title: 'Audit preparation', text: 'Schedules, reconciliations and supporting documents prepared for your external auditors, plus liaison while the audit is underway.' },
      { icon: 'fas fa-broom', title: 'Backlog clean-up', text: 'Months or years behind? We rebuild your records from bank statements and source documents and bring everything up to date.' },
      { icon: 'fas fa-coins', title: 'Multi-currency records', text: 'US$ and ZiG transactions recorded and reported correctly, so your books match how your business actually trades.' },
      { icon: 'fas fa-database', title: 'Pastel (Sage) support', text: 'Pastel setup, chart of accounts, month-end routines, troubleshooting and regular data backups.' },
    ],
    forWho: [
      'Small and medium businesses without an in-house accountant',
      'Growing companies that need monthly management information',
      'Businesses applying for bank finance or preparing for an audit',
      'Owners who are behind on their records and need a clean start',
    ],
    need: [
      'Bank statements for all business accounts',
      'Sales invoices and receipts',
      'Supplier invoices and expense receipts',
      'Payroll records (if you have staff)',
      'Last year\'s financial statements, if available',
      'Access to your accounting software, if you use one',
    ],
    faqs: [
      { q: 'How often do you need my documents?', a: 'Monthly works best. We send you a short checklist and you can share everything by email or WhatsApp, with no need to visit our office.' },
      { q: 'I\'m a year or more behind. Can you still help?', a: 'Yes. Backlog work is common. We start from your bank statements, rebuild the records and bring your books and tax filings up to date in a planned order.' },
      { q: 'Do you carry out audits?', a: 'We prepare you for audit: reconciled accounts, schedules and supporting documents. We then work alongside your appointed external auditors so the audit runs smoothly.' },
      { q: 'Which accounting software do you use?', a: 'We work extensively with Pastel (Sage) and can work with the system you already use, or recommend one that suits your business.' },
    ],
    guides: ['vat-registration-zimbabwe', 'qpd-provisional-tax'],
  },
  {
    slug: 'tax-advisory',
    name: 'Tax Advisory & ZIMRA',
    icon: 'fas fa-file-invoice-dollar',
    summary: 'Registrations, returns, tax planning, tax clearance and representation with ZIMRA.',
    lead: 'Stay fully compliant with ZIMRA and pay no more tax than the law requires. We handle registrations, returns and correspondence on your behalf.',
    intro: [
      'Zimbabwe\'s tax environment changes often, and since ZIMRA moved to its TaRMS online system many businesses have struggled with registrations, returns and tax clearance.',
      'We take that burden off you. From your first TIN to QPDs, VAT returns and ZIMRA audits, we keep you compliant, plan ahead to reduce your tax legally, and deal with ZIMRA so you don\'t have to.',
    ],
    included: [
      { icon: 'fas fa-id-card', title: 'Tax registrations', text: 'TIN, income tax, VAT and PAYE registrations completed through ZIMRA\'s TaRMS self-service portal.' },
      { icon: 'fas fa-file-lines', title: 'Returns & filings', text: 'VAT returns, QPD provisional tax, annual income tax returns (ITF12C) and withholding taxes filed accurately and on time.' },
      { icon: 'fas fa-chess', title: 'Tax planning', text: 'Structuring, timing and allowable deductions reviewed with you so you pay the right amount of tax and no more.' },
      { icon: 'fas fa-stethoscope', title: 'Tax health checks', text: 'A review of your filings, payments and ZIMRA account to find gaps and risks before ZIMRA does.' },
      { icon: 'fas fa-certificate', title: 'Tax clearance (ITF263)', text: 'We bring your returns and payments up to date so that ZIMRA\'s system issues your tax clearance, which you need for tenders and many contracts.' },
      { icon: 'fas fa-gavel', title: 'ZIMRA audits & queries', text: 'Preparation for ZIMRA audits and investigations, responses to queries and support throughout the process.' },
      { icon: 'fas fa-handshake-angle', title: 'Penalty resolution', text: 'Help engaging ZIMRA on penalties, interest and payment plans, including remission requests where there are grounds.' },
      { icon: 'fas fa-laptop', title: 'TaRMS support', text: 'Help claiming your TIN, setting up your TaRMS account and navigating the self-service portal.' },
    ],
    forWho: [
      'New businesses registering with ZIMRA for the first time',
      'Companies that are behind on returns or payments',
      'Suppliers who need a valid tax clearance for tenders and contracts',
      'Businesses that have received a ZIMRA letter, query or audit notice',
    ],
    need: [
      'Your TIN or company registration documents',
      'Previous tax returns and ZIMRA correspondence',
      'Financial statements and management accounts',
      'Bank statements for the period under review',
      'Sales and purchase records (for VAT)',
    ],
    faqs: [
      { q: 'What is TaRMS?', a: 'TaRMS (Tax and Revenue Management System) is ZIMRA\'s online platform for registrations, returns, payments and tax clearance. Taxpayers must claim their TIN and register on its self-service portal. We can do this with you.' },
      { q: 'Do I need to register for VAT?', a: 'Registration is compulsory once your taxable supplies exceed, or are expected to exceed, US$25,000 (or the ZiG equivalent) in 12 months. Businesses below the threshold can register voluntarily. See our VAT registration guide for details.' },
      { q: 'How do I get a tax clearance certificate?', a: 'Under TaRMS, tax clearance is issued to taxpayers who are up to date with all returns and payments. If yours isn\'t coming through, there is usually an outstanding return or balance, which we can find and fix.' },
      { q: 'ZIMRA has contacted me. What should I do?', a: 'Don\'t ignore it, and don\'t reply before getting advice. Send us the letter or message and we\'ll explain what it means and handle the response.' },
    ],
    guides: ['tax-clearance-itf263', 'qpd-provisional-tax', 'vat-registration-zimbabwe'],
  },
  {
    slug: 'payroll',
    name: 'Payroll Administration',
    icon: 'fas fa-users',
    summary: 'Accurate monthly payroll with PAYE, NSSA and ZIMDEF calculated and submitted on time.',
    lead: 'Your staff paid correctly and on time, with every statutory deduction calculated, submitted and recorded, every month.',
    intro: [
      'Payroll mistakes are costly: unhappy staff, ZIMRA penalties and NSSA arrears. Getting PAYE right is harder when salaries are paid in US$, ZiG or both.',
      'We run your payroll every month, apply the correct tax tables, prepare payslips and submit PAYE, NSSA and ZIMDEF on time. Your payroll information stays strictly confidential.',
    ],
    included: [
      { icon: 'fas fa-calculator', title: 'Monthly payroll processing', text: 'Salaries, allowances, overtime, benefits and deductions calculated accurately every pay period.' },
      { icon: 'fas fa-money-check-dollar', title: 'PAYE & AIDS levy', text: 'PAYE worked out with the correct US$ or ZiG tax tables and remitted to ZIMRA by the 10th of the following month.' },
      { icon: 'fas fa-shield-heart', title: 'NSSA compliance', text: 'Employer and employee NSSA registration, monthly P4 returns and contributions submitted on time.' },
      { icon: 'fas fa-graduation-cap', title: 'ZIMDEF levy', text: 'Standards development (ZIMDEF) levy calculated on your payroll and paid on schedule.' },
      { icon: 'fas fa-file-invoice', title: 'Payslips', text: 'Clear, professional payslips for every employee, delivered by email or printed.' },
      { icon: 'fas fa-user-minus', title: 'Terminations & final pay', text: 'Final salary, leave pay and tax on termination packages calculated correctly.' },
      { icon: 'fas fa-calendar-check', title: 'Year-end certificates', text: 'Employee tax certificates and the employer\'s annual PAYE return prepared at year end.' },
      { icon: 'fas fa-folder-open', title: 'Leave & payroll records', text: 'Leave balances and payroll history kept organised and ready for NSSA or ZIMRA inspection.' },
    ],
    forWho: [
      'Employers of any size, from a single employee upwards',
      'Employers paying salaries in US$, ZiG or a mix',
      'Owners who want payroll kept confidential from internal staff',
      'Companies with NSSA or PAYE arrears to regularise',
    ],
    need: [
      'Employee list with ID numbers, start dates and salaries',
      'Allowances, overtime and deductions for the month',
      'Your ZIMRA (TIN) and NSSA employer numbers',
      'Leave taken and any new starters or leavers',
    ],
    faqs: [
      { q: 'When are PAYE and NSSA due?', a: 'PAYE must reach ZIMRA by the 10th of the month after payment. NSSA contributions and the P4 return are also generally due by the 10th of the following month. We handle both for you.' },
      { q: 'We pay some staff in US$ and some in ZiG. Is that a problem?', a: 'Not at all. We apply the correct tax tables for each currency and keep your payroll records and returns consistent.' },
      { q: 'Is there a minimum number of employees?', a: 'No. We run payroll for businesses with one employee as well as larger teams.' },
      { q: 'Who sees our salary information?', a: 'Only the McDonvick staff handling your payroll. We treat all client information as strictly confidential.' },
    ],
    guides: ['employer-paye-nssa-checklist'],
  },
  {
    slug: 'company-secretarial',
    name: 'Company Secretarial',
    icon: 'fas fa-building',
    summary: 'Company and PBC registration, annual returns and statutory changes with the Registrar.',
    lead: 'Register your business correctly and keep it in good standing with the Registrar of Companies, year after year.',
    intro: [
      'The Companies and Other Business Entities (COBE) Act sets out how Zimbabwean companies and Private Business Corporations are formed and maintained. Missing filings can leave your company non-compliant just when you need it most, for a tender, a loan or a sale.',
      'We handle the paperwork from name search to certificate of incorporation, then keep your statutory records, returns and changes up to date.',
    ],
    included: [
      { icon: 'fas fa-magnifying-glass', title: 'Name search & reservation', text: 'Name search with the Registrar. Approved names are reserved for up to 30 days while registration is completed.' },
      { icon: 'fas fa-stamp', title: 'Company & PBC registration', text: 'Private Limited Company or Private Business Corporation registration under the COBE Act, through to your certificate of incorporation.' },
      { icon: 'fas fa-list-check', title: 'Post-registration setup', text: 'ZIMRA registration (TIN), NSSA employer registration and the documents your bank needs to open an account.' },
      { icon: 'fas fa-calendar-days', title: 'Annual returns', text: 'Annual returns and statutory filings with the Registrar so your company stays in good standing.' },
      { icon: 'fas fa-people-arrows', title: 'Statutory changes', text: 'Changes of directors, members, shareholders and registered office, including CR6 and CR11 filings.' },
      { icon: 'fas fa-book', title: 'Registers & minutes', text: 'Statutory registers, resolutions and minutes prepared and kept up to date.' },
      { icon: 'fas fa-right-left', title: 'Share transfers', text: 'Share and member interest transfers documented and filed correctly.' },
      { icon: 'fas fa-box-archive', title: 'Company shelving', text: 'Dormant company shelving and deregistration when a business is no longer trading.' },
    ],
    forWho: [
      'Entrepreneurs starting a new business',
      'Sole traders ready to formalise as a company or PBC',
      'Companies with overdue returns or out-of-date records',
      'Businesses changing ownership, directors or address',
    ],
    need: [
      'Five proposed company names, in order of preference',
      'Copies of IDs or passports for all directors or members',
      'Proof of residence for directors or members',
      'The business\'s physical address',
      'The ownership split between shareholders or members',
    ],
    faqs: [
      { q: 'Should I register a PBC or a Private Limited Company?', a: 'A PBC suits owner-run businesses with 1 to 20 members who manage the business themselves. A Private Limited Company (up to 50 shareholders, with directors and a company secretary) is better if you plan to raise investment or bid for larger tenders. Our guide compares them in detail.' },
      { q: 'How long does registration take?', a: 'It depends mainly on the Registrar\'s turnaround at the time. We\'ll give you a realistic estimate when you instruct us, and keep you updated at each stage.' },
      { q: 'Do I need to register with ZIMRA after incorporation?', a: 'Yes. Every company needs a TIN, and you may also need VAT and PAYE registration. We can handle this straight after incorporation.' },
      { q: 'My company hasn\'t filed returns for years. Can it be fixed?', a: 'Usually, yes. We review the company\'s status with the Registrar and file the outstanding returns to restore good standing.' },
    ],
    guides: ['company-registration-pbc-vs-pvt-ltd'],
  },
  {
    slug: 'business-consultancy',
    name: 'Business Consultancy',
    icon: 'fas fa-chart-line',
    summary: 'Business plans, forecasts, budgets and turnaround strategies that help you plan and grow.',
    lead: 'Numbers that help you plan, raise finance and grow, not just report on the past.',
    intro: [
      'Banks, investors and funders want to see that you understand your numbers. Owners need to know where the business is heading before cash runs short.',
      'We turn your figures into practical plans: business plans and projections that stand up to scrutiny, budgets you can manage against, and clear strategies when a business needs to turn around.',
    ],
    included: [
      { icon: 'fas fa-file-signature', title: 'Business plans', text: 'Bank-ready and investor-ready business plans and funding proposals, with the financials to support them.' },
      { icon: 'fas fa-arrow-trend-up', title: 'Projections & cash-flow forecasts', text: 'Three- to five-year financial projections and monthly cash-flow forecasts built on realistic assumptions.' },
      { icon: 'fas fa-wallet', title: 'Budgets & variance analysis', text: 'Annual budgets and monthly comparisons of actual against budget, so you can act early.' },
      { icon: 'fas fa-flask', title: 'Feasibility studies', text: 'Test a new product, branch or project before you commit capital to it.' },
      { icon: 'fas fa-rotate', title: 'Turnaround strategies', text: 'Cost, pricing and cash-flow reviews with a practical plan for businesses under pressure.' },
      { icon: 'fas fa-tags', title: 'Costing & pricing', text: 'Understand the true cost of your products and services and price them for profit.' },
      { icon: 'fas fa-landmark', title: 'Corporate governance', text: 'Board structures, policies and financial controls that protect the business and build trust.' },
      { icon: 'fas fa-file-circle-check', title: 'Tender support', text: 'Financial sections and compliance documents, including tax clearance, prepared for tender submissions.' },
    ],
    forWho: [
      'Start-ups raising their first finance',
      'Established businesses planning expansion',
      'NGOs and projects preparing funding proposals',
      'Businesses facing cash-flow pressure',
    ],
    need: [
      'A description of the business, project or idea',
      'Historical financial statements (for existing businesses)',
      'Key assumptions: prices, volumes, costs and staffing',
      'Any lender or funder requirements and templates',
    ],
    faqs: [
      { q: 'Will a business plan guarantee a loan?', a: 'No one can guarantee a lending decision, but a well-prepared plan with credible projections gives you the best possible chance and answers the questions lenders ask.' },
      { q: 'Can you help with tenders?', a: 'Yes. We prepare the financial information and compliance documents tenders require and check your tax clearance and company records are current.' },
      { q: 'How long does a business plan take?', a: 'It depends on the size of the project and how quickly we receive your information. We agree a timeline with you at the start.' },
    ],
    guides: ['company-registration-pbc-vs-pvt-ltd', 'tax-clearance-itf263'],
  },
];
